/*
 * Copyright 2026 niagaramcp contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.niagaramcp.server;

import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Static registry of active {@link Session}s keyed by sessionId
 * (UUID v4 generated in {@link #createSse()}; for Streamable HTTP, the
 * id is also a UUID v4 generated by the servlet on first {@code initialize}).
 *
 * <p>The registry holds the {@link Session} interface so both
 * {@link SseSession} and {@code StreamableSession} (added in commit 3)
 * coexist behind a single lookup. Closing or removing a session is
 * idempotent.
 */
public final class McpSessions {

  private static final ConcurrentHashMap<String, Session> SESSIONS = new ConcurrentHashMap<>();

  /** Create a new SSE session, register it, and return it. */
  public static SseSession createSse() {
    String id = UUID.randomUUID().toString();
    SseSession s = new SseSession(id);
    SESSIONS.put(id, s);
    BMcpPlatformService.refreshSessionCount();
    return s;
  }

  /** Create a new Streamable HTTP session, register it, and return it. */
  public static StreamableSession createStreamable() {
    String id = UUID.randomUUID().toString();
    StreamableSession s = new StreamableSession(id);
    SESSIONS.put(id, s);
    BMcpPlatformService.refreshSessionCount();
    return s;
  }

  /**
   * Look up a {@link StreamableSession} by id, applying lazy idle eviction.
   * Returns {@code null} when the id is unknown, the session has been closed,
   * the session has gone stale (older than {@code idleTimeoutMs}), or the
   * registered session is not a {@link StreamableSession}. On a successful
   * lookup the {@code lastSeenMs} marker is touched.
   */
  public static StreamableSession acquireStreamable(String sessionId, long idleTimeoutMs) {
    Session s = SESSIONS.get(sessionId);
    if (!(s instanceof StreamableSession)) return null;
    StreamableSession ss = (StreamableSession) s;
    if (ss.isClosed() || ss.isStale(idleTimeoutMs)) {
      SESSIONS.remove(sessionId);
      ss.close();
      BMcpPlatformService.refreshSessionCount();
      return null;
    }
    ss.touch();
    return ss;
  }

  /** Look up any session by id (returns the {@link Session} interface). */
  public static Session get(String sessionId) {
    return SESSIONS.get(sessionId);
  }

  public static void remove(String sessionId) {
    Session s = SESSIONS.remove(sessionId);
    if (s != null) {
      s.close();
      BMcpPlatformService.refreshSessionCount();
    }
  }

  public static void closeAll() {
    for (Session s : SESSIONS.values()) {
      s.close();
    }
    SESSIONS.clear();
    BMcpPlatformService.refreshSessionCount();
  }

  public static int activeCount() {
    return SESSIONS.size();
  }
}
